-- 코드를 입력하세요

SELECT M.MEMBER_NAME,R.REVIEW_TEXT,TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_NAME = (
    SELECT E.MEMBER_NAME
    FROM MEMBER_PROFILE E JOIN REST_REVIEW T ON E.MEMBER_ID = T.MEMBER_ID
    GROUP BY E.MEMBER_NAME
    ORDER BY COUNT(E.MEMBER_NAME) DESC
    FETCH FIRST 1 ROW ONLY
)
ORDER BY REVIEW_DATE,REVIEW_TEXT


-- SELECT E.MEMBER_NAME
-- FROM MEMBER_PROFILE E JOIN REST_REVIEW T ON E.MEMBER_ID = T.MEMBER_ID
-- GROUP BY E.MEMBER_NAME
-- ORDER BY COUNT(E.MEMBER_NAME) DESC
-- FETCH FIRST 1 ROW ONLY;